Rework and update RPM spec for HAproxy 1.6.9

diff --git a/SOURCES/haproxy.init b/SOURCES/haproxy.init
--- a/SOURCES/haproxy.init
+++ b/SOURCES/haproxy.init
@@ -1,109 +1,137 @@
 #!/bin/sh
 #
-# haproxy
-#
-# chkconfig:   - 85 15
-# description:  HAProxy is a free, very fast and reliable solution \
-#               offering high availability, load balancing, and \
-#               proxying for TCP and  HTTP-based applications
+# chkconfig: - 85 15
+# description: HA-Proxy is a TCP/HTTP reverse proxy which is particularly suited \
+#              for high availability environments.
 # processname: haproxy
-# config:      /etc/haproxy/haproxy.cfg
-# pidfile:     /var/run/haproxy.pid
+# config: /etc/haproxy/haproxy.cfg
+# pidfile: /var/run/haproxy.pid
+
+# Script Author: Simon Matter <simon.matter@invoca.ch>
+# Version: 2004060600
 
 # Source function library.
-. /etc/rc.d/init.d/functions
+if [ -f /etc/init.d/functions ]; then
+  . /etc/init.d/functions
+elif [ -f /etc/rc.d/init.d/functions ] ; then
+  . /etc/rc.d/init.d/functions
+else
+  exit 0
+fi
 
 # Source networking configuration.
 . /etc/sysconfig/network
 
 # Check that networking is up.
-[ "$NETWORKING" = "no" ] && exit 0
+[ ${NETWORKING} = "no" ] && exit 0
 
-exec="/usr/sbin/haproxy"
-prog=$(basename $exec)
+# This is our service name
+BASENAME=`basename $0`
+if [ -L $0 ]; then
+  BASENAME=`find $0 -name $BASENAME -printf %l`
+  BASENAME=`basename $BASENAME`
+fi
 
-[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog
+BIN=/usr/sbin/$BASENAME
 
-lockfile=/var/lock/subsys/haproxy
+CFG=/etc/$BASENAME/$BASENAME.cfg
+[ -f $CFG ] || exit 1
 
-check() {
-    $exec -c -V -f /etc/$prog/$prog.cfg
-}
+PIDFILE=/var/run/$BASENAME.pid
+LOCKFILE=/var/lock/subsys/$BASENAME
+
+RETVAL=0
 
 start() {
-    $exec -c -q -f /etc/$prog/$prog.cfg
-    if [ $? -ne 0 ]; then
-        echo "Errors in configuration file, check with $prog check."
-        return 1
-    fi
- 
-    echo -n $"Starting $prog: "
-    # start it up here, usually something like "daemon $exec"
-    daemon $exec -D -f /etc/$prog/$prog.cfg -p /var/run/$prog.pid
-    retval=$?
-    echo
-    [ $retval -eq 0 ] && touch $lockfile
-    return $retval
+  quiet_check
+  if [ $? -ne 0 ]; then
+    echo "Errors found in configuration file, check it with '$BASENAME check'."
+    return 1
+  fi
+
+  echo -n "Starting $BASENAME: "
+  daemon $BIN -D -f $CFG -p $PIDFILE
+  RETVAL=$?
+  echo
+  [ $RETVAL -eq 0 ] && touch $LOCKFILE
+  return $RETVAL
 }
 
 stop() {
-    echo -n $"Stopping $prog: "
-    # stop it here, often "killproc $prog"
-    killproc $prog 
-    retval=$?
-    echo
-    [ $retval -eq 0 ] && rm -f $lockfile
-    return $retval
+  echo -n "Shutting down $BASENAME: "
+  killproc $BASENAME -USR1
+  RETVAL=$?
+  echo
+  [ $RETVAL -eq 0 ] && rm -f $LOCKFILE
+  [ $RETVAL -eq 0 ] && rm -f $PIDFILE
+  return $RETVAL
 }
 
 restart() {
-    $exec -c -q -f /etc/$prog/$prog.cfg
-    if [ $? -ne 0 ]; then
-        echo "Errors in configuration file, check with $prog check."
-        return 1
-    fi
-    stop
-    start
+  quiet_check
+  if [ $? -ne 0 ]; then
+    echo "Errors found in configuration file, check it with '$BASENAME check'."
+    return 1
+  fi
+  stop
+  start
 }
 
 reload() {
-    $exec -c -q -f /etc/$prog/$prog.cfg
-    if [ $? -ne 0 ]; then
-        echo "Errors in configuration file, check with $prog check."
-        return 1
-    fi
-    echo -n $"Reloading $prog: "
-    $exec -D -f /etc/$prog/$prog.cfg -p /var/run/$prog.pid -sf $(cat /var/run/$prog.pid)
-    retval=$?
-    echo
-    return $retval
+  if ! [ -s $PIDFILE ]; then
+    return 0
+  fi
+
+  quiet_check
+  if [ $? -ne 0 ]; then
+    echo "Errors found in configuration file, check it with '$BASENAME check'."
+    return 1
+  fi
+  $BIN -D -f $CFG -p $PIDFILE -sf $(cat $PIDFILE)
 }
 
-force_reload() {
-    restart
+check() {
+  $BIN -c -q -V -f $CFG
 }
 
-fdr_status() {
-    status $prog
+quiet_check() {
+  $BIN -c -q -f $CFG
 }
 
+rhstatus() {
+  status $BASENAME
+}
+
+condrestart() {
+  [ -e $LOCKFILE ] && restart || :
+}
+
+# See how we were called.
 case "$1" in
-    start|stop|restart|reload)
-        $1
-        ;;
-    force-reload)
-        force_reload
-        ;;
-    check)
-        check
-        ;;
-    status)
-        fdr_status
-        ;;
-    condrestart|try-restart)
-  	[ ! -f $lockfile ] || restart
-	;;
-    *)
-        echo $"Usage: $0 {start|stop|status|restart|try-restart|reload|force-reload}"
-        exit 2
+  start)
+    start
+    ;;
+  stop)
+    stop
+    ;;
+  restart)
+    restart
+    ;;
+  reload)
+    reload
+    ;;
+  condrestart)
+    condrestart
+    ;;
+  status)
+    rhstatus
+    ;;
+  check)
+    check
+    ;;
+  *)
+    echo $"Usage: $BASENAME {start|stop|restart|reload|condrestart|status|check}"
+    exit 1
 esac
+ 
+exit $?
